# Generated by Django 3.1.2 on 2021-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_mrp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
