# Generated by Django 3.1.2 on 2021-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_auto_20210206_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
