# Generated by Django 3.1.2 on 2021-02-06 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_auto_20210206_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
