# Generated by Django 3.1.2 on 2021-02-06 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_mrp', models.IntegerField(blank=True, null=True)),
                ('item_rate', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.customer')),
            ],
        ),
    ]
