# Generated by Django 3.1.2 on 2021-02-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0007_estimates'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estimates.item'),
        ),
    ]
