# Generated by Django 3.1.2 on 2021-02-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_auto_20210206_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rate',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.unit'),
        ),
    ]
