# Generated by Django 3.1.2 on 2021-02-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0012_auto_20210206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='estimate_name',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
