# Generated by Django 3.1.2 on 2021-02-06 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0013_auto_20210206_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=10)),
                ('customer_email_address', models.CharField(blank=True, max_length=50)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Added')),
            ],
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='estimate',
            new_name='estimates',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='customer',
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_name',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Estimate Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Added'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='estimates',
            name='customers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estimates.customers'),
        ),
    ]
