# Generated by Django 3.1.2 on 2021-02-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0014_auto_20210206_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.customers'),
        ),
    ]
